[build]
  functions = "functions/"
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NETLIFY_USE_YARN = "true"

[template.environment]
  API_URL = "your Google Maps API endpoint"
  API_TOKEN = "your Google Maps API key"

[[redirects]]
from="/api"
to=".netlify/functions/getapi"
status=200
